# Create a copy of this file as user.settings.yml and modify the settings as per your desire
user:
  fullname: Firstname Lastname
  email: john.doe@example.com
  lang: en_US.utf8
settings:
  system:
    use_proxy: false
    http_proxy: ''
    https_proxy: ''
    no_proxy: 'localhost, 172.0.0.1'

box:
  name: example
  distro: boxcutter/centos73-desktop
  desktop_environment: Gnome
  usb2: true
  memory: 4096
  cpus: 2
  monitorcount: 2
  paravirtprovider: default
  portforwardings:
    - name: example
      protocol: tcp
      host-port: 80
      guest-port: 80
  shares:
    share:
      host: D:\PATH\TO\code
      guest: /home/vagrant/Documents

ansible:
  # Roles to install
  roles: ["atom", "wowza"]