# Use this file to set project specific config
user:
  keyboard_layout: en
settings:
  system:
    use_proxy: false
    http_proxy: ''
    https_proxy: ''
    no_proxy: 'localhost, 172.0.0.1'

box:
  usb2: true
  memory: 4096
  cpus: 2
  monitorcount: 2
  portforwardings:
    - name: tomcat
      protocol: tcp
      host_port: 8080
      guest_port: 8080

ansible:
  # Roles to install
  roles: ["atom"]
