- name: update http_proxy settings
  template:
    src: proxy.sh.j2
    dest: /etc/profile.d/proxy.sh
    mode: 0644
    owner: root
    group: root

# Lasts way to long.
#- name: Update yum itself
#  become: true
#  shell: "yum -y update"


- name: install some generic used elements
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - yum-utils
    - "@Development tools"
    - git


- name: set keyboard layout(s) No.1
  become: true
  shell: "localectl set-keymap {{ user.keyboard_layouts }}"
- name: set keyboard layout(s) No.2
  become: true
  shell: "localectl set-x11-keymap {{ user.keyboard_layouts }}"


- name: "prevent initial setup popup (https://seven.centos.org/2013/12/preventing-gnome3s-initial-setup/)"
  when: "box.desktop_environment|lower == 'gnome'"
  copy:
    dest: /home/vagrant/.config/gnome-initial-setup-done
    content: yes

- name: create cache dir if not exists
  file:
    dest: "{{ download_cache_dir }}"
    state: directory
